### ISSUE TITLE
Preview Window Is Not Working.

### ISSUE THREAD

**Issue by josephanimate2021** [offline-revision/revision#1]
can you please fix it? thanks.

**Comment by NolanJTheSuperGoAnimator** [comment]
I'll take care of it because people won't even accept your statement knowing them.

**Comment by josephanimate2021** [comment]
actually, after i tested it in another browser i have, i would like to say that i am proud that you tried to fix it. thanks boi. this issue is now closed.

**Comment by NolanJTheSuperGoAnimator** [comment]
Yeah, no problem, but, I didn't fix it, the devs probably did, but like yeah, they might not be working a few times, but most of the time, they work, so, yeah. But thank you anyway.
