### ISSUE TITLE
Hey, some people, especially NathanSaturnBOI and the Joseph guy are having a LOT of trouble with the preview window, so can you please fix it? I'd really appreciate it if you do. Thanks.

### ISSUE THREAD

**Issue by NolanJTheSuperGoAnimator** [offline-revision/revision#2]

**Comment by sparrkzz** [comment]
What's the problem specifically? It's working fine for me. I'm gonna need you to elaborate more.

**Comment by NolanJTheSuperGoAnimator** [comment]
Um, it is actually the import window that they're having trouble with, like when they click the import button, then the import window wouldn't open, so, can you please fix it? I would appreciate it. Thanks.

**Comment by sparrkzz** [comment]
were they trying this on recent commits?

**Comment by NolanJTheSuperGoAnimator** [comment]
Well, nevermind for now.
