### ISSUE TITLE
Business Friendly Is Not Working

### ISSUE THREAD

**Issue by josephanimate2021** [offline-revision/revision#3]
hi, when I tried loading the backgrounds for business friendly, they don't load at all! and I know the cause for that. you did not put in enough stock characters in the characters folder! the stock characters only work for comedy world and we do not want that at all! so I am demanding that you put in 79,384 stock characters right this instant! if you don't, then I will have no choice but to put them in for you! I have all the files needed to get business friendly working even though you renamed it to "Modern World"

**Comment by Thunderzapper** [comment]
lol
